In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

### Scalar, Vector, Matrix, Tensor

In [3]:
scalar = torch.tensor(7)
scalar
# A scalar is a single number, write as lower case (x,y,z)

tensor(7)

In [3]:
vector = torch.tensor([1,2])  # [] indicate 1 dimension, this is 1x1 matrix
# A number with direction, like a point in a 1D grid, write as lower case (x,y,z)
print(vector)
print(vector.ndim)
print(vector.shape)

tensor([1, 2])
1
torch.Size([2])


In [4]:
MAXTRIX = torch.tensor([[1,2],
                        [3,4]])  # [[]] indicate 2 dimension, this is 2x2 matrix
                                 # Imagine a 2D grid x,y. If you mark out the coordinate of the tensor, you get 2 points
                                 # From those 2 points, draw a line perpendicular to the x-axis and the y-axis, you get a 2x2 matrix
# A matrix is a 2D grid of numbers, write as upper case (X,Y,Z)
print(MAXTRIX)
print(MAXTRIX.ndim)
print(MAXTRIX.shape)

tensor([[1, 2],
        [3, 4]])
2
torch.Size([2, 2])


In [5]:
TENSOR = torch.tensor([[[1,2,3],
                        [4,5,6],
                        [7,8,9]]])  # this is 3D, 1x3x3 matrix
                                    # the same goes for this tensor, draw out the x,y,z grid and do the same thing as above
# A tensor is an n-dimensional grid of numbers, write as upper case (X,Y,Z)
print(TENSOR)
print(TENSOR.ndim)
print(TENSOR.shape)

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])
3
torch.Size([1, 3, 3])


### Random Tensor


Random tensor is the way how neural network learns, they take in crap and process through many epoch to get results. Those result aren't going to be optimal and may require many epoch to reach its most optimal form. If the number of epoch is not handle with care, it may overfit the model

Start with random number -> process data -> get result -> compare result with actual data -> adjust the model -> repeat 
That is 1 cycle or 1 epoch

In [6]:
random_tensor_matrix = torch.rand(3,3)  # Argument is the shape of the tensor
random_tensor_matrix

tensor([[0.6367, 0.1821, 0.4329],
        [0.0773, 0.2604, 0.8853],
        [0.3976, 0.7634, 0.9084]])

In [7]:
random_tensor_tensor = torch.rand(1,3,3)
print(random_tensor_tensor)

tensor([[[0.8225, 0.5873, 0.9205],
         [0.5286, 0.4331, 0.2565],
         [0.5432, 0.1095, 0.6904]]])


Random Image Tensor

In [8]:
random_image_tensor = torch.rand(size=(1920,1080,3))  # size=(width, height, color channel) color channel is RGB
#random_image_tensor = torch.rand(size=(3,1080,1920))   size=(color channel, height, width) is fine
# Let say you have an image with 1920x1080 resolution compact with 3 color channel: Red, Green and Blue
# The tensor will take the image and split it into 3 color channel
random_image_tensor

tensor([[[0.5470, 0.6917, 0.2896],
         [0.3030, 0.5080, 0.8564],
         [0.3006, 0.7739, 0.9914],
         ...,
         [0.6135, 0.9080, 0.4648],
         [0.0507, 0.7956, 0.5716],
         [0.5450, 0.3637, 0.5883]],

        [[0.0192, 0.5474, 0.8520],
         [0.9231, 0.4058, 0.7445],
         [0.6092, 0.2069, 0.9067],
         ...,
         [0.6392, 0.6253, 0.7496],
         [0.6993, 0.0503, 0.8571],
         [0.6060, 0.1818, 0.6628]],

        [[0.0985, 0.7736, 0.6471],
         [0.1562, 0.9470, 0.5502],
         [0.6551, 0.3307, 0.8451],
         ...,
         [0.8329, 0.6716, 0.2617],
         [0.4471, 0.8160, 0.8034],
         [0.0054, 0.9270, 0.8438]],

        ...,

        [[0.6548, 0.8278, 0.8129],
         [0.8732, 0.6648, 0.7095],
         [0.4947, 0.2611, 0.6466],
         ...,
         [0.1825, 0.0968, 0.6552],
         [0.5583, 0.6992, 0.8072],
         [0.4823, 0.4259, 0.9328]],

        [[0.3398, 0.8156, 0.1077],
         [0.1205, 0.7580, 0.7397],
         [0.

Zeros and Ones Tensor

In [117]:
zero = torch.zeros(size=(3,3)) 
zero

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [10]:
one = torch.ones(size=(3,3))
one

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

Range of tensors and tensors-like

In [13]:
torch.arange(0,5,1)  # start, end, step

tensor([0, 1, 2, 3, 4])

In [20]:
tensor_like = torch.zeros_like(one)  # zeros_like is similar to zeros but the shape is the given tensor
tensor_like

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

### Tensor Datatype
**Note:** Tensor datatype have 3 main errors:
1. **Type Error**: When you try to do operation with different datatype
2. **Shape Error**: When you try to do operation with different shape
3. **Device Error**: When you try to use the tensor on different device (cpu, gpu), **JUST USE THE GPU(cuda)**

In [ ]:
torch.tensor([[1,2],
              [3,4]], dtype=torch.float32,  # Default is float32, has int32, complex32, bool, ...)
                      device='cuda',  # Default is 'cpu' but change it to 'cuda' for GPU
                      requires_grad=False)  # Default is False, this is for backpropagation

# Use this code to set all tensor to using the gpu and avoid Device Error
with torch.cuda.device(0):
    t1 = torch.tensor([[1, 2, 3], [4, 5, 6]])
    t2 = torch.tensor([[7, 8, 9], [10, 11, 12]])

In [26]:
torch.Tensor([[1,2],
              [3,4]])  # Different from torch.tensor, this can create tensor like normal
torch.Tensor(2,2)  # But if pass in size instead of a particular tensor, it will create a random tensor

tensor([[0., 0.],
        [0., 0.]])

In [7]:
# This code is use for setting the device to gpu and showing the memory usage
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print('Using device:', device)
print()

# Additional Info when using cuda
if device.type == 'cuda':
    print(torch.cuda.get_device_name(0))
    print('Memory Usage:')
    print('Allocated:', round(torch.cuda.memory_allocated(0)/1024**3,1), 'GB')
    print('Cached:   ', round(torch.cuda.memory_reserved(0)/1024**3,1), 'GB')

Using device: cuda

NVIDIA GeForce RTX 4060 Laptop GPU
Memory Usage:
Allocated: 0.0 GB
Cached:    0.0 GB


### Tensor Operations
1. **Addition**
2. **Subtraction**
3. **Multiplication**
4. **Division**
5. **Matrix Multiplication**: When multiplying 2 matrix together, the number of column in the first matrix must be equal to the number of row in the second matrix (axb * cxd = axd if b=c => axb * bxd = axd) if forgot basic go to http://matrixmultiplication.xyz

In [13]:
test = torch.tensor([[1,2,3],
                     [4,5,6],
                     [7,8,9]])
print(test + 10)  # torch.add(test, 10)
print(test - 10)  # torch.sub(test, 10)
print(test * 10)  # torch.mul(test, 10)
print(test / 10)  # torch.div(test, 10)
print(torch.matmul(test, test))
print(test.mT)  # Transpose the matrix

tensor([[[11, 12, 13],
         [14, 15, 16],
         [17, 18, 19]]])
tensor([[[-9, -8, -7],
         [-6, -5, -4],
         [-3, -2, -1]]])
tensor([[[10, 20, 30],
         [40, 50, 60],
         [70, 80, 90]]])
tensor([[[0.1000, 0.2000, 0.3000],
         [0.4000, 0.5000, 0.6000],
         [0.7000, 0.8000, 0.9000]]])
tensor([[[ 30,  36,  42],
         [ 66,  81,  96],
         [102, 126, 150]]])
tensor([[[1, 4, 7],
         [2, 5, 8],
         [3, 6, 9]]])


### Min, Max, Sum, Mean, Mode, Median ...

In [35]:
test = torch.tensor([[1,2,3],
                     [4,5,6],
                     [7,8,9]])
print(test.min())
print(test.argmin())  # Find the position of the min value
print(test.max())
print(test.argmax())  # Find the position of the max value
print(test.sum())
print(test.mean(dtype=torch.float32))  # Mean must take a float or complex number and int is a Long

tensor(1)
tensor(0)
tensor(9)
tensor(8)
tensor(45)
tensor(5.)


### Reshape, Squeeze, Unsqueeze, Flatten, Stack

In [113]:
test = torch.tensor([[1,2,3],
                     [4,5,6],
                     [7,8,9]])
print(torch.arange(1,10,1))  # Give a 1D tensor from 1 to 9 with 1 step
print(test.reshape(1,9))  # Reshape the tensor to 1x9, multiplication must be equal: 3x3 = 1x9
print(test.view(1,9))  # Same as reshape but if change test then view will also change

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])
tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]])
tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]])
tensor([[1, 4, 7],
        [2, 5, 8],
        [3, 6, 9]])


In [116]:
test = torch.tensor([[1,2,3],
                     [4,5,6],
                     [7,8,9]])
tensor = torch.randn(1, 3, 5, 1, 2, 1)
print(torch.stack((test, test)).shape)  # Stack = add 2 dimentions at place 0 -> max-1
print(test.unsqueeze(0).shape)  # Unsqueeze = add 1 dimentions at place 0 -> max-1


print(tensor.squeeze(0,3).shape)  # Remove 1D tensor in specific place
print(tensor.squeeze().shape)  # Remove all 1D tensor
print(tensor.permute(5,2,0,4,3,1).shape)  # Rearrange the tensor using their index

torch.Size([2, 3, 3])
torch.Size([1, 3, 3])
torch.Size([3, 5, 2, 1])
torch.Size([3, 5, 2])
torch.Size([1, 5, 1, 2, 1, 3])


### Indexing and Slicing

In [180]:
test = torch.tensor([[1,2,3],
                     [4,5,6],
                     [7,8,9]])
test = test.unsqueeze(0)
# Given a 1xaxb matrix
print(test[0])  # Get value at 3x3
print(test[0,0])  # Get value at 3x1
print(test[0,1,2])  # Get value at 1x3x2
print(test[0,0:2,0])  # Get value at 1x1x1 and 1x2x1
print(test[0,0:2,0:3])
print(test[:,:,1].shape)  # : = select all = 0:2
print(test[0,0:3,1].shape)
### Everytime selecting an index, the dimentions got reduce by 1
### Example: test = 1x3x3, test[0] = 3x3, test[0,0] = 3, test[0,0,0] = 1D-array

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
tensor([1, 2, 3])
tensor(6)
tensor([1, 4])
tensor([[1, 2, 3],
        [4, 5, 6]])
torch.Size([1, 3])
torch.Size([3])


### Numpy


In [214]:
num = np.arange(0,5)  # Convert numpy to tensor
tensor = torch.from_numpy(num)  # numpy always use x64
backwards = tensor.numpy()  # Convert tensor to numpy
print(tensor.dtype)

''' When changing value in tensor, the numpy will also change but not the other way around
to prevent this, change the data type of the tensor to x32 before modifying the value '''
num_convert = np.arange(0,5)
tensor_convert = torch.from_numpy(num_convert).type(torch.int32)  # Change the data type to x32
print(tensor_convert.dtype)

tensor[0] = -100
tensor_convert[0] = -100
print('Without conversion (numy):',num)
print('Without conversion (tensor):',tensor,'\n')
print('With conversiom (numy):', num_convert)
print('With conversiom (numy):', tensor_convert)

torch.int64
torch.int32
Without conversion (numy): [-100    1    2    3    4]
Without conversion (tensor): tensor([-100,    1,    2,    3,    4]) 

With conversiom (numy): [0 1 2 3 4]
With conversiom (numy): tensor([-100,    1,    2,    3,    4], dtype=torch.int32)


### Reproducibility (take random out of random)

**How NN learn:** Start with random number -> process data -> get result -> compare result with actual data -> adjust the model -> repeat

**Manual Seed:** Set a specific random number to the next torch.rand

***
**torch.rand**: 
1. Set the random number from [0,1), use when data is uniformly distributed
2. If want to set the random number from [a,b), use torch.randint(a,b) or **x_new = torch.rand * (b-a) + a**

**torch.randn**:
 1. Set the random number from normal distribution with mean = 0 and std = 1, use when data is normally distributed
2. If want to set the random number from [a,b), use **x_new = torch.randn * std + mean**

In [37]:
torch.manual_seed(999)
tensorA = torch.rand(2,2)
torch.manual_seed(999)
tensorB = torch.rand(2,2)
tensorA, tensorB, tensorA == tensorB


(tensor([[0.6776, 0.6531],
         [0.0457, 0.9424]]),
 tensor([[0.6776, 0.6531],
         [0.0457, 0.9424]]),
 tensor([[True, True],
         [True, True]]))

### Accessing the GPU and CPU

**Note:** Numpy cannot use the GPU, only tensor can use the GPU

In [85]:
tensor = torch.tensor([1,2,3])
tensor = tensor.cuda()
print(tensor.device)
# print(tensor.numpy())  # This will cause an error
tensor = tensor.cpu()  # Change the tensor back to using CPU
print(tensor.device)
print(tensor.numpy())

cuda:0
cpu
[1 2 3]
